### ISSUE TITLE
Typing any query into the upper left search box produces link to Authors search page

### ISSUE THREAD

**Issue by eawoods** [cul-it/arxiv-search#36] opened 2018-02-05 15:45 UTC
Anything typed into the mini box on the upper right goes to the last query page from which one started a search, without performing search or displaying results. It does preserve and send along the mini box query, for example:
http://127.0.0.1:5000/search/authors?query=first&searchtype=Title

**Comment by erickpeirson** [comment] 2018-02-05 16:37
I believe it's because the ``action`` on the mini form is not set. This relates to ARXIVNG-204: Flask gives us URL generation for in-service links, but we need to implement a cross-service URL builder in base.

**Comment by erickpeirson** [comment] 2018-02-09 00:26
This should be fixed with ``base-0.2``, forthcoming

**Comment by eawoods** [comment] 2018-02-09 14:26
I'm going to assign this task to you, then? My feeling is that any task that's tagged for current release should be assigned (feel free to assign remaining tasks to anyone as you see fit).

**Comment by erickpeirson** [comment] 2018-02-09 18:55
Confirmed that this is fixed in https://github.com/cul-it/arxiv-base/releases/tag/0.2.1

**Closed by erickpeirson** 2018-02-09 18:55 UTC
Labels: release 0.1
