### ISSUE TITLE
Should "Subject" field search secondary as well as primary classifications?

### ISSUE THREAD

**Issue by eawoods** [cul-it/arxiv-search#40] opened 2018-02-05 16:51 UTC
I recognize that implementing secondaries may not yet be in the plan (we don't display them in the results yet either), but generally I think a subject search would turn up both primaries and secondaries, and we could facet on the position (or use as a relevance indicator).

Example: https://arxiv.org/abs/physics/0001066 "The Genetic Code as a Periodic Table: Algebraic Aspects" is classified as physics.bio-ph and secondarily as q-bio, but only findable by searching physics.

**Comment by erickpeirson** [comment] 2018-02-12 16:46
Given that primary classification has domain significance, I'd be tempted to make this optional. Eg, "limit to primary" or "include secondaries"

**Comment by erickpeirson** [comment] 2018-02-20 20:42
Out of scope for 0.1; let's leave open for the next release.

**Comment by erickpeirson** [comment] 2018-10-31 01:15
This is a dupe of https://github.com/cul-it/arxiv-search/issues/209 ; going to close this one to consolidate.

**Closed by erickpeirson** 2018-10-31 01:15 UTC
